In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])

In [12]:
print("array1 type : ",type(array1))
#x축값 3개 y축값 0개 -> 0개일시 표시 안됨
print("array1.shape : ", array1.shape)

array1 type :  <class 'numpy.ndarray'>
array1.shape :  (3,)


In [8]:
array2 = np.array([[1,2,3],[4,5,6]])

In [11]:
print("array2 type : ",type(array2))
print("arrat2.shape : ", array2.shape)

array2 type :  <class 'numpy.ndarray'>
arrat2.shape :  (2, 3)


In [13]:
array3 = np.array([[1,2,3]])

In [14]:
print("array3 type : ", type(array3))
print("array3.shape", array3.shape)

array3 type :  <class 'numpy.ndarray'>
array3.shape (1, 3)


In [26]:
array4 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [27]:
#z축=3 y축=2 x축=2
#가장 겉의 "[,]"개수로 차원 알 수 있음
print("array4 type : ", type(array4))
print("array4.shape", array4.shape)

array4 type :  <class 'numpy.ndarray'>
array4.shape (3, 2, 2)


In [28]:
print("arr1 : {}차원, arr2 : {}차원, arr3 : {}차원, arr4 : {}차원".format(array1.ndim, array2.ndim, array3.ndim, array4.ndim))

arr1 : 1차원, arr2 : 2차원, arr3 : 2차원, arr4 : 3차원


In [29]:
list1 = [1,2,3]
print(type(list1))

<class 'list'>


In [30]:
arr = np.array(list1)
print(type(arr))
print(arr, arr.dtype)

<class 'numpy.ndarray'>
[1 2 3] int32


In [31]:
#ndarray는 리스트와 다르게 다른 데이터타입을 담지 못하고 더 큰 자료형으로 변환하여 하나로 통합시킴
list2 = [1,2,"test"]
arr2 = np.array(list2)
print(arr2, arr2.dtype)

list3 = [1,2,3.0]
arr3 = np.array(list3)
print(arr3, arr3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [32]:
arr_int = np.array([1,2,3])
arr_float = arr_int.astype("float64")
print(arr_float, arr_float.dtype)

[1. 2. 3.] float64


In [33]:
arr_int1 = arr_float.astype("int32")
print(arr_int1, arr_int1.dtype)

[1 2 3] int32


In [34]:
arr_float1 = np.array([1.1,2.2,3.3,4.4])
arr_int2 = arr_float1.astype("int32")
print(arr_int2, arr_int2.dtype)

[1 2 3 4] int32


In [36]:
#array + range -> arange()
seq_arr = np.arange(10)
print(seq_arr)
print(seq_arr.dtype, seq_arr.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [39]:
zero_arr = np.zeros((3,2), dtype="int32")
print(zero_arr)
print(zero_arr.dtype, zero_arr.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [44]:
one_arr = np.ones((3,2))
print(one_arr)
print(one_arr.dtype, one_arr.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [45]:
array1 = np.arange(10)
print("array1 : ",array1)

array1 :  [0 1 2 3 4 5 6 7 8 9]


In [46]:
array2 = array1.reshape(2,5)
print("Array2 : ",array2)

Array2 :  [[0 1 2 3 4]
 [5 6 7 8 9]]


In [47]:
array3 = array1.reshape(5,2)
print("array3 : ", array3)

array3 :  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [50]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print("array2 : ",array2.shape)
array3 = array1.reshape(5,-1)
print("array3 : ", array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 :  (2, 5)
array3 :  (5, 2)


In [52]:
array1 = np.arange(8)
arr3d = array1.reshape((2,2,2))
print("arr3d : ", arr3d.tolist())

arr3d :  [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [62]:
#reshape를 통한 2차원으로 고정변환 가능
array5 = arr3d.reshape(-1,1)
print("array5 : ",array5.tolist())
print("array5.shape : ",array5.shape)

array5 :  [[0], [1], [2], [3], [4], [5], [6], [7]]
array5.shape :  (8, 1)


In [60]:
array6 = array1.reshape(-1,1)
print("array6 : ", array6.tolist())
print("array6.shape : ",array6.shape)

array6 :  [[0], [1], [2], [3], [4], [5], [6], [7]]
array6.shape :  (8, 1)


In [63]:
array1 = np.arange(start = 1, stop=10)
array2 = array1[0:3]
print(array2)
print(type(array2))

[1 2 3]
<class 'numpy.ndarray'>


In [68]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print("array2d\n : ",array2d)

print("array2d[0:2, 0:2]\n",array2d[0:2, 0:2])
print("array2d[1:3, 0:3]\n",array2d[1:3, 0:3])
print("array2d[1:3, :]\n",array2d[1:3, :])
print("array2d[:, :]\n",array2d[:, :])
print("array2d[:-1, 1:]\n",array2d[:-1, 1:])

array2d
 :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:-1, 1:]
 [[2 3]
 [5 6]]


In [69]:
print(array2d[0])
print(array2d[1])

[1 2 3]
[4 5 6]


In [71]:
#팬시 인덱싱 = 0:2 -> [0,1]으로 묶어준것과 같음
array3 = array2d[[0,1],2]
print("arrat2d[[0,1],2] : ", array3.tolist())

arrat2d[[0,1],2] :  [3, 6]


In [77]:
array4 = array2d[[0,1], 0:2]
print("array2d[[0,1],0:2] : ", array4.tolist())

array2d[[0,1],0:2] :  [[1, 2], [4, 5]]


In [75]:
array5 = array2d[[0,1]]
print("array2d[[0,1]] : ", array5.tolist())

array2d[[0,1]] :  [[1, 2, 3], [4, 5, 6]]


In [79]:
array2 = array1d[array1d > 5]

In [80]:
print("arrat1d > 5 불린 인덱싱 값 : ", array2)

arrat1d > 5 불린 인덱싱 값 :  [6 7 8 9]


In [90]:
#불릭 인덱싱시에 F,T로 이루어진 ndarray반환
print(array1d > 5)
type(array1d)

[False False False False False  True  True  True  True]


numpy.ndarray

In [92]:
boolean_index = np.array([False,True,False,True,False,True,False,True,False])
array3 = array1d[boolean_index]
print("불리언 인덱싱으로 필터링 결과 : ",array3)

불리언 인덱싱으로 필터링 결과 :  [2 4 6 8]


In [94]:
index = ([1,3,5,7])
array4 = array1d[index]
print("일반 인덱싱 필터링 결과 : ",array4)

일반 인덱싱 필터링 결과 :  [2 4 6 8]


In [95]:
org_array = np.array([3,1,9,5])
print("origin array : ", org_array)
sort_array1 = np.sort(org_array)
print("np.sort array : ",sort_array1)
print("origin array : ", org_array)
sort_array2 = org_array.sort()
print("ndarray.sort array : ",sort_array2)
print("origin array : ", org_array)

origin array :  [3 1 9 5]
np.sort array :  [1 3 5 9]
origin array :  [3 1 9 5]
ndarray.sort array :  None
origin array :  [1 3 5 9]


In [96]:
sort_array_desc = np.sort(org_array)[::-1]
print("descending : ",sort_array_desc)

descending :  [9 5 3 1]


In [97]:
array2d = np.array([[8,12],[7,1]])

In [100]:
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print("axis0 sort : \n", sort_array2d_axis0)
sort_array2d_axis1 = np.sort(array2d, axis = 1)
print("axis1 sort : \n", sort_array2d_axis1)

axis0 sort : 
 [[ 7  1]
 [ 8 12]]
axis1 sort : 
 [[ 8 12]
 [ 1  7]]


In [101]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print("행렬 정렬 시 원본 행렬의 인덱스 : ",sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 :  [1 0 3 2]


In [102]:
sort_indices_desc = np.argsort(org_array)[::-1]
print("index's desc : ",sort_indices_desc)

index's desc :  [2 3 0 1]


In [107]:
name_array = np.array(["Ann","Bee","Carl","Dole","Eric"])
score_array = np.array([100,95,60,12,50])

sort_indices_asc = np.argsort(score_array)
print("오름차순 정렬 : ",sort_indices_asc)
print("오름차순 정렬 이름 출력 : ",name_array[sort_indices_asc])

오름차순 정렬 :  [3 4 2 1 0]
오름차순 정렬 이름 출력 :  ['Dole' 'Eric' 'Carl' 'Bee' 'Ann']


In [109]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8],[9,10],[11,12]])
dot_array = np.dot(a,b)
print("내적결과 : \n",dot_array)

내적결과 : 
 [[ 58  64]
 [139 154]]


In [112]:
a=np.array([[1,2],[3,4]])
trans_mat = np.transpose(a)
print("a의 전치행렬 : \n",trans_mat)

a의 전치행렬 : 
 [[1 3]
 [2 4]]
